version: '2.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: 'mysite'
        MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
        timeout: 5s
        retries: 3
    ports:
      - "3302:3306"
    container_name: mysql
  web:
    container_name: web
    restart: always
    image: web
    build: ./
    volumes:
      - ./:/code
    ports:
      - "8011:8000"
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
