# Generated by Django 2.2.5 on 2020-01-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0003_auto_20200109_1326'),
        ('category', '0003_auto_20200109_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategoryRelation',
            fields=[
                ('id', models.IntegerField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
    ]
