# Generated by Django 2.2.5 on 2020-01-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newscategoryrelation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategoryrelation',
            name='news_id',
        ),
    ]
