# Generated by Django 2.2.5 on 2020-01-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200109_1326'),
        ('newscategoryrelation', '0002_remove_newscategoryrelation_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategoryrelation',
            name='news_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.News'),
            preserve_default=False,
        ),
    ]
