# Generated by Django 2.2.5 on 2020-01-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200109_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.IntegerField(editable=False, max_length=50),
        ),
    ]
